services:
  chhoto-url:
    image: sintan1729/chhoto-url:latest
    container_name: chhoto-url
    restart: unless-stopped
    tty: true

    expose:
      - "4567"

    environment:
      db_url: ${db_url}
      password: ${password}
      site_url: ${site_url}
      api_key: ${api_key}
      use_wal_mode: ${use_wal_mode}
      redirect_method: ${redirect_method}
      cache_control_header: ${cache_control_header}

    volumes:
      - chhoto-url-data:/data

volumes:
  chhoto-url-data:
